apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
#  local:
#    push: false
  googleCloudBuild:
    projectId: ticketing-dev-454417
  artifacts:
    - image: us.gcr.io/ticketing-dev-454417/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
